openapi: 3.0.1
info:
  contact:
    email: NuoDB.Support@3ds.com
    url: https://nuodb.com
  description: NuoDB Control Plane (CP) allows users to create and manage NuoDB databases
    remotely using a Database as a Service (DBaaS) model.
  license:
    name: NuoDB EULA
    url: https://doc.nuodb.com/nuodb/latest/release-notes/license-terms/nuodb-eula/
  termsOfService: https://doc.nuodb.com/nuodb/latest/release-notes/nuodb-license-terms/
  title: NuoDB Control Plane REST API
  version: 2.2.0
servers:
- url: https://example.nuodb.com
paths:
  /databases/{organization}/{project}/{database}:
    delete:
      operationId: deleteDatabase
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: database
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The database was deleted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The database does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Delete an existing database
      tags:
      - databases
    get:
      operationId: getDatabase
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: database
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseModel'
          description: The database was found
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The database does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Get an existing database
      tags:
      - databases
    patch:
      operationId: patchDatabase
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: database
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json-patch+json:
            examples:
              "0":
                summary: Change database tier
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/tier",
                      "value": "n1.small"
                    }
                  ]
              "1":
                summary: Increase disk size for database archives
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/properties/archiveDiskSize",
                      "value": "100Gi"
                    }
                  ]
              "2":
                summary: Set database to expire
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/maintenance",
                      "value": {
                        "expiresIn": "1d"
                      }
                    }
                  ]
              "3":
                summary: Disable database
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/maintenance",
                      "value": {
                        "isDisabled": true
                      }
                    }
                  ]
              "4":
                summary: Enable database
                value: |-
                  [
                    {
                      "op": "remove",
                      "path": "/maintenance"
                    }
                  ]
            schema:
              items:
                $ref: '#/components/schemas/JsonPatchOperation'
              type: array
        required: true
      responses:
        "200":
          description: The patch was applied to the database
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The database does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The database could not be updated due to unexpected state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json-patch+json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Update an existing database
      tags:
      - databases
    put:
      operationId: createDatabase
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: database
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              "0":
                summary: Create database
                value: |-
                  {
                    "tier": "n0.small",
                    "dbaPassword": "changeIt",
                    "properties": {
                      "archiveDiskSize": "50Gi",
                      "journalDiskSize": "5Gi"
                    }
                  }
              "1":
                summary: Create database with default properties
                value: |-
                  {
                    "dbaPassword": "changeIt"
                  }
              "2":
                summary: Update database
                value: |-
                  {
                    "organization": "acme",
                    "project": "messaging",
                    "name": "demo",
                    "tier": "n1.small",
                    "properties": {
                      "archiveDiskSize": "100Gi",
                      "journalDiskSize": "10Gi"
                    },
                    "resourceVersion": "30503"
                  }
            schema:
              $ref: '#/components/schemas/DatabaseCreateUpdateModel'
        required: true
      responses:
        "200":
          description: The database was updated
        "201":
          description: The database was created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: "The database could not be created because the project does\
            \ not exist, or could not be updated because it does not exist"
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The database could not be created or updated due to unexpected
            state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Create or update a database
      tags:
      - databases
  /databases/{organization}/{project}:
    get:
      operationId: getDatabases
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemListString'
          description: The list of databases was returned
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: List the databases in a project
      tags:
      - databases
  /healthz:
    get:
      operationId: getHealth
      responses:
        "204":
          description: The server is healthy
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The server is unhealthy
      security:
      - basicAuth: []
      summary: Get health of service
      tags:
      - healthz
  /projects/{organization}/{project}:
    delete:
      operationId: deleteProject
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The project was deleted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project could not be deleted because it has databases
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Delete an existing project
      tags:
      - projects
    get:
      operationId: getProject
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectModel'
          description: The project was found
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Get an existing project
      tags:
      - projects
    patch:
      operationId: patchProject
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json-patch+json:
            examples:
              "0":
                summary: Change project tier
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/tier",
                      "value": "n0.small"
                    }
                  ]
              "1":
                summary: Set project to expire
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/maintenance",
                      "value": {
                        "expiresIn": "1d"
                      }
                    }
                  ]
              "2":
                summary: Disable project
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/maintenance",
                      "value": {
                        "isDisabled": true
                      }
                    }
                  ]
              "3":
                summary: Enable project
                value: |-
                  [
                    {
                      "op": "remove",
                      "path": "/maintenance"
                    }
                  ]
            schema:
              items:
                $ref: '#/components/schemas/JsonPatchOperation'
              type: array
        required: true
      responses:
        "200":
          description: The patch was applied to the project
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project could not be updated due to unexpected state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json-patch+json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Update an existing project
      tags:
      - projects
    put:
      operationId: createProject
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: project
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              "0":
                summary: Create project
                value: |-
                  {
                    "sla": "dev",
                    "tier": "n0.nano"
                  }
              "1":
                summary: Update project
                value: |-
                  {
                    "organization": "acme",
                    "name": "messaging",
                    "sla": "dev",
                    "tier": "n0.small",
                    "resourceVersion": "30503"
                  }
            schema:
              $ref: '#/components/schemas/ProjectModel'
        required: true
      responses:
        "200":
          description: The project was updated
        "201":
          description: The project was created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project could not be updated because it does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The project could not be created or updated due to unexpected
            state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Create or update a project
      tags:
      - projects
  /projects/{organization}:
    get:
      operationId: getProjects
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemListString'
          description: The list of projects was returned
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: List the projects in an organization
      tags:
      - projects
  /users/{organization}/{user}:
    delete:
      operationId: deleteUser
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: user
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The user was deleted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Delete an existing user
      tags:
      - users
    get:
      operationId: getUser
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: user
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DbaasUserModel'
          description: The user was found
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user does not exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Get an existing user
      tags:
      - users
    patch:
      operationId: patchUser
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: user
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to allow the user to have access outside of its organization
        explode: true
        in: query
        name: allowCrossOrganizationAccess
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json-patch+json:
            examples:
              "0":
                summary: Change user password
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/password",
                      "value": "newPassword"
                    }
                  ]
              "1":
                summary: Change user access
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/accessRule",
                      "value": {
                        "allow": [
                          "read:acme",
                          "all:acme/messaging"
                        ]
                      }
                    }
                  ]
              "2":
                summary: Grant read access for organization
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/accessRule/allow/-",
                      "value": "read:acme"
                    }
                  ]
              "3":
                summary: Grant full access for project
                value: |-
                  [
                    {
                      "op": "add",
                      "path": "/accessRule/allow/-",
                      "value": "all:acme/messaging"
                    }
                  ]
            schema:
              items:
                $ref: '#/components/schemas/JsonPatchOperation'
              type: array
        required: true
      responses:
        "200":
          description: The patch was applied to the user
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user could not be updated due to unexpected state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json-patch+json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Update an existing user
      tags:
      - users
    put:
      operationId: createUser
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: user
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to allow the user to have access outside of its organization
        explode: true
        in: query
        name: allowCrossOrganizationAccess
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            examples:
              "0":
                summary: Create user
                value: |-
                  {
                    "password": "changeIt",
                    "accessRule": {
                      "allow": [
                        "all:acme"
                      ]
                    }
                  }
              "1":
                summary: Update user
                value: |-
                  {
                    "organization": "acme",
                    "name": "admin",
                    "password": "newPassword",
                    "accessRule": {
                      "allow": [
                        "all:acme"
                      ]
                    },
                    "resourceVersion": "30503"
                  }
            schema:
              $ref: '#/components/schemas/DbaasUserCreateUpdateModel'
        required: true
      responses:
        "200":
          description: The user was updated
        "201":
          description: The user was created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user could not be updated because it does not exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user could not be created or updated due to unexpected
            state
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A media type other than `application/json` was supplied
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: Create or update a user
      tags:
      - users
  /users/{organization}:
    get:
      operationId: getUsers
      parameters:
      - explode: false
        in: path
        name: organization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemListString'
          description: The list of users was returned
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user request was invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user did not provide correct authentication credentials
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: The user was not authorized to access the requested resource
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContentString'
          description: A server error occurred
      security:
      - basicAuth: []
      summary: List the users in an organization
      tags:
      - users
components:
  schemas:
    DatabaseCreateUpdateModel:
      example:
        tier: n0.small
        organization: organization
        resourceVersion: resourceVersion
        name: name
        project: project
        dbaPassword: dbaPassword
        maintenance:
          expiresIn: 1d
          expiresAtTime: 2024-01-01T00:00:00Z
          isDisabled: true
        properties:
          journalDiskSize: 50Gi
          archiveDiskSize: 2Ti
        status:
          sqlEndpoint: sqlEndpoint
          ready: true
          caPem: caPem
          message: message
          shutdown: true
      properties:
        organization:
          pattern: "[a-z][a-z0-9]*"
          type: string
        project:
          pattern: "[a-z][a-z0-9]*"
          type: string
        name:
          pattern: "[a-z][a-z0-9]*"
          type: string
        dbaPassword:
          description: The password for the DBA user. Can only be specified when creating
            a database.
          type: string
          writeOnly: true
        tier:
          description: "The service tier for the database. If omitted, the project\
            \ service tier is inherited."
          example: n0.small
          type: string
        maintenance:
          $ref: '#/components/schemas/MaintenanceModel'
        properties:
          $ref: '#/components/schemas/DatabasePropertiesModel'
        resourceVersion:
          description: "The version of the resource. When specified in a `PUT` request\
            \ payload, indicates that the resoure should be updated, and is used by\
            \ the system to guard against concurrent updates."
          type: string
        status:
          $ref: '#/components/schemas/DatabaseStatusModel'
      type: object
    DatabasePropertiesModel:
      example:
        journalDiskSize: 50Gi
        archiveDiskSize: 2Ti
      properties:
        archiveDiskSize:
          description: The size of the archive volumes for the database. Can be only
            updated to increase the volume size.
          example: 2Ti
          pattern: "^(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE])?$"
          type: string
        journalDiskSize:
          description: The size of the journal volumes for the database. Can be only
            updated to increase the volume size.
          example: 50Gi
          pattern: "^(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE])?$"
          type: string
      type: object
    DatabaseStatusModel:
      example:
        sqlEndpoint: sqlEndpoint
        ready: true
        caPem: caPem
        message: message
        shutdown: true
      properties:
        sqlEndpoint:
          description: The endpoint for SQL clients to connect to
          type: string
        caPem:
          description: The PEM-encoded certificate for SQL clients to verify database
            servers
          type: string
        ready:
          description: Whether the database is ready
          type: boolean
        shutdown:
          description: Whether the database has shutdown
          type: boolean
        message:
          description: Message summarizing the state of the database
          type: string
      readOnly: true
      type: object
    MaintenanceModel:
      example:
        expiresIn: 1d
        expiresAtTime: 2024-01-01T00:00:00Z
        isDisabled: true
      properties:
        expiresAtTime:
          description: The time at which the project or database will be disabled
          example: 2024-01-01T00:00:00Z
          format: date-time
          type: string
        expiresIn:
          description: "The time until the project or database is disabled, e.g. `1d`"
          example: 1d
          pattern: "(\\d+)\\s*([A-Za-zµ]+)"
          type: string
        isDisabled:
          description: Whether the project or database should be shutdown
          type: boolean
      type: object
    DatabaseModel:
      example:
        tier: n0.small
        organization: organization
        resourceVersion: resourceVersion
        name: name
        project: project
        maintenance:
          expiresIn: 1d
          expiresAtTime: 2024-01-01T00:00:00Z
          isDisabled: true
        properties:
          journalDiskSize: 50Gi
          archiveDiskSize: 2Ti
        status:
          sqlEndpoint: sqlEndpoint
          ready: true
          caPem: caPem
          message: message
          shutdown: true
      properties:
        organization:
          pattern: "[a-z][a-z0-9]*"
          type: string
        project:
          pattern: "[a-z][a-z0-9]*"
          type: string
        name:
          pattern: "[a-z][a-z0-9]*"
          type: string
        tier:
          description: "The service tier for the database. If omitted, the project\
            \ service tier is inherited."
          example: n0.small
          type: string
        maintenance:
          $ref: '#/components/schemas/MaintenanceModel'
        properties:
          $ref: '#/components/schemas/DatabasePropertiesModel'
        resourceVersion:
          description: "The version of the resource. When specified in a `PUT` request\
            \ payload, indicates that the resoure should be updated, and is used by\
            \ the system to guard against concurrent updates."
          type: string
        status:
          $ref: '#/components/schemas/DatabaseStatusModel'
      type: object
    ItemListString:
      example:
        items:
        - items
        - items
      properties:
        items:
          items:
            type: string
          type: array
      type: object
    JsonNode:
      oneOf:
      - type: object
      - type: string
      - type: number
      - type: boolean
      type: object
    JsonPatchOperation:
      example:
        op: add
        path: path
        from: from
        value: null
      properties:
        op:
          enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
          type: string
        from:
          pattern: /.*
          type: string
        path:
          pattern: /.*
          type: string
        value:
          $ref: '#/components/schemas/JsonNode'
      required:
      - op
      - path
      type: object
    ProjectModel:
      example:
        tier: n0.small
        organization: organization
        resourceVersion: resourceVersion
        name: name
        sla: dev
        maintenance:
          expiresIn: 1d
          expiresAtTime: 2024-01-01T00:00:00Z
          isDisabled: true
        status:
          ready: true
          caPem: caPem
          message: message
          shutdown: true
      properties:
        organization:
          pattern: "[a-z][a-z0-9]*"
          type: string
        name:
          pattern: "[a-z][a-z0-9]*"
          type: string
        sla:
          description: The SLA for the project. Cannot be updated once the project
            is created.
          example: dev
          type: string
        tier:
          description: The service tier for the project
          example: n0.small
          type: string
        maintenance:
          $ref: '#/components/schemas/MaintenanceModel'
        resourceVersion:
          description: "The version of the resource. When specified in a `PUT` request\
            \ payload, indicates that the resoure should be updated, and is used by\
            \ the system to guard against concurrent updates."
          type: string
        status:
          $ref: '#/components/schemas/ProjectStatusModel'
      required:
      - sla
      - tier
      type: object
    ProjectStatusModel:
      example:
        ready: true
        caPem: caPem
        message: message
        shutdown: true
      properties:
        caPem:
          description: The PEM-encoded certificate for SQL clients to verify database
            servers within the project
          type: string
        ready:
          description: Whether the project is ready
          type: boolean
        shutdown:
          description: Whether the project and all of its databases have shutdown
          type: boolean
        message:
          description: Message summarizing the state of the project
          type: string
      readOnly: true
      type: object
    DbaasAccessRuleModel:
      description: The rule specifying access for the user
      example:
        allow:
        - allow
        - allow
        deny:
        - deny
        - deny
      properties:
        allow:
          description: "List of access rule entries in the form `<verb>:<resource\
            \ specifier>[:<SLA>]` that specify requests to allow"
          items:
            type: string
          type: array
        deny:
          description: List of access rule entries in the form `<verb>:<resource specifier>`
            that specify requests to deny
          items:
            type: string
          type: array
      type: object
    DbaasUserCreateUpdateModel:
      example:
        password: password
        organization: organization
        resourceVersion: resourceVersion
        name: name
        accessRule:
          allow:
          - allow
          - allow
          deny:
          - deny
          - deny
      properties:
        organization:
          pattern: "[a-z][a-z0-9]*"
          type: string
        name:
          pattern: "[a-z][a-z0-9]*"
          type: string
        password:
          description: The password for the user
          type: string
          writeOnly: true
        accessRule:
          $ref: '#/components/schemas/DbaasAccessRuleModel'
        resourceVersion:
          description: "The version of the resource. When specified in a `PUT` request\
            \ payload, indicates that the resoure should be updated, and is used by\
            \ the system to guard against concurrent updates."
          type: string
      required:
      - accessRule
      type: object
    DbaasUserModel:
      example:
        organization: organization
        resourceVersion: resourceVersion
        name: name
        accessRule:
          allow:
          - allow
          - allow
          deny:
          - deny
          - deny
      properties:
        organization:
          pattern: "[a-z][a-z0-9]*"
          type: string
        name:
          pattern: "[a-z][a-z0-9]*"
          type: string
        accessRule:
          $ref: '#/components/schemas/DbaasAccessRuleModel'
        resourceVersion:
          description: "The version of the resource. When specified in a `PUT` request\
            \ payload, indicates that the resoure should be updated, and is used by\
            \ the system to guard against concurrent updates."
          type: string
      required:
      - accessRule
      type: object
    ErrorContentString:
      properties:
        code:
          type: string
        status:
          type: string
        detail:
          type: string
      type: object
  securitySchemes:
    basicAuth:
      scheme: BASIC
      type: http
